<a href="https://colab.research.google.com/github/Aditya089081/DATA-SCIENCE-TOOLBOX-PYTHON-PROGRAMMING/blob/main/Pandas_pracrice(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
s1 = pd.Series([1,2,3,4,5,6,7])
s2 = pd.Series([3,4,5,6,7,8,9],index=(['a','b','c','d','e','f','g']))
print(s1)
s3 = pd.Series({'a':1,'b':2,'c':3})
print(s3)
print(s3.keys())
print(s3[-3:2])
s3=s3+5
print(s3)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64
a    1
b    2
c    3
dtype: int64
Index(['a', 'b', 'c'], dtype='object')
a    1
b    2
dtype: int64
a    6
b    7
c    8
dtype: int64

In [4]:
s4 = pd.DataFrame({'aditya':[1,2,3,4,5,6,7],'tiwari':[3,4,5,6,7,8,9]})
print(s4)

   aditya  tiwari
0       1       3
1       2       4
2       3       5
3       4       6
4       5       7
5       6       8
6       7       9

In [7]:
iris = pd.read_csv('/content/phone_usage.csv')
# iris.head()
iris.describe()

,Age,Screen Time (hrs/day),Data Usage (GB/month),Calls Duration (mins/day),Number of Apps Installed,Social Media Time (hrs/day),E-commerce Spend (INR/month),Streaming Time (hrs/day),Gaming Time (hrs/day),Monthly Recharge Cost (INR),Unnamed: 16,Unnamed: 17
count,17686.000000,17687.000000,17686.000000,17686.000000,17686.000000,17686.000000,17686.000000,17686.000000,17686.000000,17686.000000,0.0,0.0
mean,37.584247,6.546376,25.411257,151.405846,104.584869,3.252369,5075.707848,4.250616,2.490857,1042.785367,NaN,NaN
std,13.338252,3.172588,14.122167,84.923353,55.217097,1.590223,2871.604841,2.155683,1.446007,552.502067,NaN,NaN
min,15.000000,1.000000,1.000000,5.000000,10.000000,0.500000,100.000000,0.500000,0.000000,100.000000,NaN,NaN
25%,26.000000,3.800000,13.200000,77.325000,57.000000,1.900000,2587.500000,2.400000,1.200000,561.000000,NaN,NaN
50%,38.000000,6.600000,25.300000,150.600000,104.000000,3.200000,5052.000000,4.200000,2.500000,1040.000000,NaN,NaN
75%,49.000000,9.300000,37.600000,223.900000,152.000000,4.600000,7606.000000,6.100000,3.700000,1521.750000,NaN,NaN
max,60.000000,12.000000,50.000000,300.000000,200.000000,6.000000,10000.000000,8.000000,5.000000,2000.000000,NaN,NaN

# New Section